### ISSUE TITLE
iOS app crashes when switching tours

### ISSUE THREAD

**Issue by jollopre** [edina/CuriousEdinburgh2#102]
Anytime a tour is switched and the user taps on any marker, the app crashes. 

Scenario:
- Open the app with the default tour
- Change tour
- Tap any marker

It might be related to #95

**Comment by adrianczuczka** [comment]
I think this issue was fully fixed in my pull request, even though it might be good to check on iPhone, since I could only test it on Android.

**Comment by NicolaOsborne** [comment]
Adrian, I'm afraid this is still an issue on iOS - have just tested and confirmed this. Happy for you to use my phone to view and then test the fix.

**Comment by adrianczuczka** [comment]
I see, then that would be great, as I don't have an iPhone at my disposal.

**Comment by adrianczuczka** [comment]
I added another commit to fix a problem with setting markers' zIndexes, and it should now correctly update them. Again, it is probably good to try it on iPhone but it does work on Android. My changes are in my fork, in branch "issue-102-app-crashes", so you can clone that and try it. I'll also open an issue regarding the back button functionality on Android (and workarounds on iOS) if that's ok.

**Comment by NicolaOsborne** [comment]
@adrianczuczka @jollopre I presume we will we need to issue a new app update to get this onto our users devices?

**Comment by adrianczuczka** [comment]
We might want to wait a bit because I'm working on the UI right now, so if you guys will agree with the changes I'll make, we can issue a big update rather than many small ones

**Comment by NicolaOsborne** [comment]
This has been tested again in Test Flight and the crashing persists.
